### ISSUE TITLE
Add the script for Money.

### ISSUE THREAD

**Issue by mashfiqui-rabbi** [StatisticalReinforcementLearningLab/SARAv2#10]
Add the service to give money. There is no need to create a new branch. Please send me pull request by today if possible (Feb 12).

**Comment by lxh37** [comment]
Dan's code already added money? no need to add branch, you mean to add it directly to your ADAPTSbranchv2?

**Comment by lxh37** [comment]
I just checked, award-dollar.service.ts is already under survey folder, what else you need?

**Comment by mashfiqui-rabbi** [comment]
Does this code give extra money on day 1?

**Comment by lxh37** [comment]
Nope, I just added service, Dan hooks up awardDallar in userprofile/localstorage, he can answer this question more
accurately.

Liying
________________________________

**Comment by mashfiqui-rabbi** [comment]
Liying, I assigned it to myself. I found the "award-dollar.service.ts."

**Comment by mashfiqui-rabbi** [comment]
This issue has been closed. Now "award-dollar.service.ts" pays 1 for each three-day streak.
