### ISSUE TITLE
Add money to userprofile

### ISSUE THREAD

**Issue by mashfiqui-rabbi** [StatisticalReinforcementLearningLab/SARAv2#13]
Add the money to userprofile. Currently the "award-money-service.ts" provides money locally.

**Comment by mashfiqui-rabbi** [comment]
@dan-chop-ris is money added to the user profile now?

**Comment by dan-chop-ris** [comment]
Yes. Via the dollars property - based on three day streaks. 
I had not yet added the $1 for first day.  (I still need clarification if that is for the first day they take a survey or the first they're enrolled in the study.)  If you'd like we can keep this issue open for adding that $1.

**Comment by mashfiqui-rabbi** [comment]
Dan, I added $1 for the first day. We don't need to take care of it.

**Comment by mashfiqui-rabbi** [comment]
See this commit.
https://github.com/StatisticalReinforcementLearningLab/SARAv2/commit/d21d6de53eda54208afb9fe5c7f4ac7064f340c1#diff-71774bbff97c90d629a9a922ec5742aa

**Comment by dan-chop-ris** [comment]
Fixed in Dan one signal #15
