### ISSUE TITLE
Stop survey from the server

### ISSUE THREAD

**Issue by mashfiqui-rabbi** [StatisticalReinforcementLearningLab/SARAv2#22]
For this issue, please create a branch directly from "AdaptsBranchV3"

**Comment by dan-chop-ris** [comment]
Mash - is it okay if I hide the survey button when the account is paused.  
(With the last merge into V3, it should now display the text "Account is Paused" when the account is paused. ) 
Or should we keep the button, but display a message with more info about it being paused when they tap the button (who paused it, why it's paused, when it will be unpaused, etc.)

**Comment by mashfiqui-rabbi** [comment]
Hi Dan,
Can use texts like "Start Survey" or "Survey paused"?

**Comment by dan-chop-ris** [comment]
Do you remain the Survey icon button with the text "Start Survey"?

**Comment by mashfiqui-rabbi** [comment]
Yes, the text "Start survey" instead of the icon.
