### ISSUE TITLE
Store meme data in user profile

### ISSUE THREAD

**Issue by mashfiqui-rabbi** [StatisticalReinforcementLearningLab/SARAv2#29]

**Comment by dan-chop-ris** [comment]
Is this looking like:
```
"20170430": {
            "ds": 1, //means participants completed the survey
            "prob": 0.23,
            "Like": "yes", //no if participants hated it.
            "reward": 1,  //0 means users were not randomized
            "reward_type": "meme", //'altruistic message'
            "reward_img_link": "img/reinforcements/memes/IM25.jpg"
}
```
in the reinforcement property?

**Comment by mashfiqui-rabbi** [comment]
yes dan, it should be in the 'reinforcement_data' property.

**Comment by mashfiqui-rabbi** [comment]
How is this work going?

**Comment by dan-chop-ris** [comment]
I was waiting for the last merge (from pull request #30) since I'll also be modifying the UserProfile in this issue as well.  I decided to proceed regardless this morning.  So, we're moving forward now.

**Comment by mashfiqui-rabbi** [comment]
Thanks Dan, if you are stuck please send me a text directly. The slack channel is too active sometimes so I can't sometime keep track what Liying and you are talking about.
