### ISSUE TITLE
Change prob and routing for aya and caregiver after submit survey

### ISSUE THREAD

**Issue by lxh37** [StatisticalReinforcementLearningLab/SARAv2#40]

**Comment by mashfiqui-rabbi** [comment]
Liying to confirm:

**AYA probability**:
- Nothing with probability: 0.33
- Meme with probability: 0.33
- Altruistic messages: 0.33

**Care-giver probability**: 
- Directly take to the aquarium

**Comment by lxh37** [comment]
In the meeting, I was told to do below, want to change
again?


AYA probability:

  *   Nothing with probability: 0.4
  *   Meme with probability: 0.3
  *   Altruistic messages: 0.3

Care-giver probability:

  *   Directly take to the aquarium

Liying

**Comment by mashfiqui-rabbi** [comment]
This one works as well. Just make sure we are storing the prob in the "Nothing with probability" on the survey page.

**Comment by mashfiqui-rabbi** [comment]
Did you change this Liying?

**Comment by lxh37** [comment]
Not sure what you mean, if you mean if I did the following:


AYA probability:

  *   Nothing with probability: 0.4
  *   Meme with probability: 0.3
  *   Altruistic messages: 0.3

Care-giver probability:

  *   Directly take to the aquarium

My answer is Yes.

Liying

________________________________

**Comment by mashfiqui-rabbi** [comment]
Awesome. I am closing this issue then :-)
