### ISSUE TITLE
Reduce long delay and blank webpage during login

### ISSUE THREAD

**Issue by mashfiqui-rabbi** [StatisticalReinforcementLearningLab/SARAv2#44]
The loading screen waits too long and doesn't provide any feedback when it fails.

**Comment by mashfiqui-rabbi** [comment]
@dan-chop-ris  I tried to find this loading screen. Do you know where the code is coming from?

**Comment by dan-chop-ris** [comment]
@mashfiqui-rabbi - do you mean  the spinner that comes up after you click login?

**Comment by mashfiqui-rabbi** [comment]
Yes... is this the "ion-spinner"? Also, how does it time-out and show a blank page?

**Comment by dan-chop-ris** [comment]
Yes.  It's the ion-spinner.  Which is in the auth.component in User module.
In auth.component.ts, in the Submit method, in the subscribe there's authObs.subscribe which subscribes to authService.login and in there, there's a subscribe to userProfileService.initializeObs, and in there, depending on the response there's a few different cases, all of which turn off the spinner.
