### ISSUE TITLE
Add S3 for CHOP Server

### ISSUE THREAD

**Issue by mashfiqui-rabbi** [StatisticalReinforcementLearningLab/SARAv2#6]
Currently, we are storing data to our dev S3 bucket. Swtich bucket to CHOP version

**Comment by lxh37** [comment]
Just receive an email, wonder if this assignment is closed?

**Comment by mashfiqui-rabbi** [comment]
Liying, the issue isn't closed. I will send an email on how to create a branch, make edit, send a pull request for review.

**Comment by mashfiqui-rabbi** [comment]
Please make sure the CHOP credentials are not shared.
