### ISSUE TITLE
Upload Reinforcement data to S3

### ISSUE THREAD

**Issue by mashfiqui-rabbi** [StatisticalReinforcementLearningLab/SARAv2#60]
Liying isn't uploading entire reinforcement data to S3. She basically replicated the data we had in the CSV file.

**Comment by lxh37** [comment]
I was instructed to upload only data according to csv file when I asked if I need
to upload same reinforcement data to server...

________________________________

**Comment by mashfiqui-rabbi** [comment]
This is done
