### ISSUE TITLE
Add one-signal environmental variables, iOS/Android testing

### ISSUE THREAD

**Issue by mashfiqui-rabbi** [StatisticalReinforcementLearningLab/SARAv2#9]
Add the one-signal environment credentials in the AdaptBranchV2. Also, redo the iOS notification and see if the notification is received.

**Comment by dan-chop-ris** [comment]
Just clarification.  
1) Do you mean point to the credentials in the environment file and use them instead of hard coding them?
2)  Regarding redoing iOS notification; does the iOS specific configuration need to be done in xCode and if so, is that outside the scope of the Ionic project?

**Comment by mashfiqui-rabbi** [comment]
Dan, can you add the stuff you posted me on slack on Feb 5? i.e., money, survey paused, and the following line:

>  this.oneSignal.startInit(environment.oneSignalAppId, environment.firebaseConfig.messagingSenderId);

I will update the issue with the changes you made and close it.

**Comment by dan-chop-ris** [comment]
So, I should create a new branch with the updates described in my DM to you in Slack on Feb 5 and the line you referenced above?  And you'll update the description of this issue then close it when you merge?

**Comment by mashfiqui-rabbi** [comment]
Yes, dan, when you are done, send me a pull request and I will merge it to the main branch. Once it is merged then delete your branch.

**Comment by dan-chop-ris** [comment]
Fixed in PR Dan one signal #15
